language: c
branches:
  only:
    - master
    - work
sudo: required
dist: trusty
git:
  depth: false
cache:
  timeout: 1000
  directories:
    - build
services:
  - docker
install:
  - chmod +x build-ubuntu-18.04.sh
after_success:
  - docker --version
