sudo: required
language: c
python:
  - "3.6"
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - gcc-6
    - python3
    - python3-pip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ninja build-essential
  - sudo pip3 install meson
  - python3 -V
  - pip3 -V

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
script:
  - mkdir build
  - meson build
  - cd build
  - ninja
  - ninja test
