sudo: false
dist: "trusty"
language: "c"
compiler:
  - "gcc"
env:
  - TRAVIS_PYTHON_VERSION=3.5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - gcc-6
    - python3
    - python3-pip
    - dbus
    - libdbus-1-dev
before_install:
  - "sudo apt-get -qq update"
  - "sudo apt-get install ninja build-essential"
  - "sudo python3 -m pip install pathlib"
  - "sudo python3 -m pip install meson==0.42.1"
  - "python3 -V"

script:
  - meson . build
  - cd build
  - ninja
  - ninja test
    #notifications:
    #irc:
    #channels:
