sudo: required
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - gcc-6
    - python3
    - python-pip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ninja build-essential
  - sudo pip install meson==0.42.1
  - python3 -V

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
script:
  - meson . build
  - cd build
  - ninja
  - ninja test
